# Generated by Django 3.0.5 on 2020-05-07 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('capacity', models.IntegerField()),
                ('price_base', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField(choices=[(0, '9:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00'), (10, '19:00'), (11, '20:00')])),
                ('end_hour', models.IntegerField(choices=[(0, '9:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00'), (9, '18:00'), (10, '19:00'), (11, '20:00')])),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('in_shopping_cart', models.BooleanField(default=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.Installation')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('range_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='reservations.RangeHours')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='sports',
            field=models.ManyToManyField(related_name='installations', to='reservations.Sport'),
        ),
    ]
