# Generated by Django 3.0.5 on 2020-05-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_event_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.Event'),
        ),
    ]
