# Generated by Django 3.0.5 on 2020-05-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200515_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.Event'),
        ),
    ]
