# Generated by Django 3.0.5 on 2020-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200515_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='events', to='reservations.Team'),
        ),
    ]
