# Generated by Django 3.0.5 on 2020-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200515_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='events', to='reservations.Team'),
        ),
    ]
